### PR TITLE
Node v20 support

### PR DESCRIPTION
**Pull request by j0d0nn**
**Issue #2654**

**Description of changes:**

Adds v20 to the list of supported node versions and v10 to the supported npm versions. The only non-test code that was changed was the way to get at the webcrypto API, which now requires going through the `node:crypto` package.

**Testing:**

Tested using `npm run test` against a local node 20.10.0. I also installed the built package into my personal app that's using Node 20 and verified the functionality (audio only and data messages, but it works!).

**Checklist:**

1. Have you successfully run `npm run build:release` locally?
yes - the docs end up modified because the URLs point to my fork; not committing those.

2. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved?
no

3. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved?
no

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by j0d0nn** [comment]
@hensmi-amazon @ltrung apologies for the direct ping (looking at recent active committers), but I was hoping I could get permission to run CI on this PR?

**Comment by xuesichao** [comment]
Hi @j0d0nn Thanks for your contribution. Unfortunately our repo does not allow us to give access to external contributor. Let me check out your commit and verify your PR.

**Comment by j0d0nn** [comment]
Thank you @xuesichao ! Looks like a ton of failures, but most of them seem to be environmental if I'm reading it right?

**Comment by xuesichao** [comment]
@j0d0nn, the failures were anticipated. The CI can obtain credentials only when a PR is initiated by members of the Amazon Chime SDK JS Dev. I've cherry-picked your commit and raised PR #2827. Therefore, we will be co-authors of this change. Thank you for your contribution, and for resolving the build error by implementing the `getCrypot` method and unit tests. That helps a lot.

**Pull request closed without merging**
