### PR TITLE
Update 20_Builders_Journey.md

### PR DESCRIPTION
**Pull request by albrich-me**
Added Customer Journey table

**Issue #:**

**Description of changes:**

**Testing:**

*Can these tested using a demo application? Please provide reproducible step-by-step instructions.*

**Checklist:**

1. Have you successfully run `npm run build:release` locally?

2. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved?

3. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by michhyun1** [comment]
Need to pull from the main branch and re-submit the PR

**Review by michhyun1 — APPROVED** [review]

**Comment by michhyun1** [comment]
`Have you successfully run npm run build:release locally?`

Please follow the guidelines for publishing PR's shown in the PR description. If you run this command, the build step won't fail when submitting the PR.

**Comment by ralbertson99** [comment]
I edited the doc on the web gui so I could not run npm run.  I’m fairly new to this so any documents you can point me to would be appreciated.

**Comment by michhyun1** [comment]
I'll create a new PR with your changes - I hope you don't mind. We need to run some commands before submitting the PR.

**Pull request closed without merging**
