### PR TITLE
Updated documentation for default downlink policy

### PR DESCRIPTION
**Pull request by gustavofamorim**
**Issue #1887:**
Previously, the default downlink policy for simulcast was changed from `AllHighestVideoBandwidthPolicy` to `VideoAdaptiveProbePolicy` (https://github.com/aws/amazon-chime-sdk-js/pull/1614 and referenced in https://github.com/aws/amazon-chime-sdk-js/issues/1887#issuecomment-998323487).

The current documentation still metioning the `AllHighestVideoBandwidthPolicy` as the default policy in modules documentation page [`/modules/qualitybandwidth_connectivity.html`](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html) without mentioning that the simulcast default policy is different. This PR tries to improve the documentation to better clarify this.

**Description of changes:**
Updated documentation for default downlink policy to mention what is the default downlink policy when simulcast is enabled.

**Testing:**

*Can these tested using a demo application? Please provide reproducible step-by-step instructions.*

**Checklist:**

1. Have you successfully run `npm run build:release` locally?
Yes

2. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved?
No

3. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved?
No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ltrung** [comment]
@gustavofamorim Can you update the markdown file under guides instead? You can then run npm run doc to generate the doc files.

**Comment by gustavofamorim** [comment]
> @gustavofamorim Can you update the markdown file under guides instead? You can then run npm run doc to generate the doc files.

Done!

**Comment by ltrung** [comment]
@gustavofamorim Can you commit the doc files?

**Review by ltrung — APPROVED** [review]

**Comment by ltrung** [comment]
Thank @gustavofamorim

**Pull request merged**
