### PR TITLE
Hotfix/globalthis is not defined (critical)

### PR DESCRIPTION
**Pull request by rlebosse**
**Issue #:** https://github.com/aws/amazon-chime-sdk-js/issues/908

**Description of changes:** Check that `globalThis` is defined before trying to extract `globalThis['AudioWorkletNode']`

**Testing**

1. Have you successfully run `npm run build:release` locally?
2. How did you test these changes?
3. Can these changes be tested using the demo application? If yes, which demo application can be used to test it?
4. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved?
5. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rnewman** [comment]
Thanks for the PR, @rlebosse.

`globalThis` is available in all browsers that the Amazon Chime SDK supports:

https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#Browser_compatibility

Can you tell us where you're seeing issues?

Additionally, the code in `libs` is imported from a separate repo; this change would need to be made upstream.

**Comment by rlebosse** [comment]
I'm facing the error as soon as I import some code from `amazon-chime-sdk-js`.

No need to try to execute some code from the `amazon-chime-sdk-js` lib to get the error, the import is enough.

In my own opinion, that should not be the case due to the fact that we need to be able to call `new BrowserBehavior().isSupported()` to know if the current browser is supported by the JS SDK.

**Comment by rnewman** [comment]
Which browser are you using?

**Comment by rlebosse** [comment]
I ran into the issue on Edge 18 / IE 11 / Chrome 67

**Comment by rnewman** [comment]
I would be quite surprised if SDK code loads at all in IE11, because it necessarily uses ES2015 syntax like `class`, and successfully transpiling classes that extend built-in classes (e.g., `AudioWorkletNode`) to ES5 is quite tricky: if you want to support IE, you will likely need to use code splitting in Webpack or some other mechanism to deliver different code to legacy browsers.

I am preparing an upstream change to introduce a guard similar to the one in this PR, and extend it to the support check, also.

**Comment by richnew10** [comment]
#910 just landed; please test against `master` and reopen #908 if needed.

**Comment by rlebosse** [comment]
@richnew10 , I tested against `master`, it works perfectly, the error is gone, thanks a lot for your reactivity !

**Comment by richnew10** [comment]
Glad to hear it! This will go out with the next dot release; it's safe for you to track `master` in the interim.

**Pull request closed without merging**
