### PR TITLE
Delete duplicate code in `demos/browser/server.js` file

### PR DESCRIPTION
**Pull request by dahae0320**
**Issue #:** N/A

**Description of changes:**
Delete duplicate else-if statements in demo app, server.js file. (pathname: end)
* Duplicate code locations: `demos/browser/server.js`
   * lines 209 to 214, lines 311 to 315

**Testing:**

*Can these tested using a demo application? Please provide reproducible step-by-step instructions.*
No.

**Checklist:**

1. Have you successfully run `npm run build:release` locally?
y

2. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved?
n

3. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved?
n

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by hensmi-amazon** [comment]
unfortunately our integration tests do not work with external forks. I will move it to a remote branch when i get a chance

**Comment by dahae0320** [comment]
> unfortunately our integration tests do not work with external forks. I will move it to a remote branch when i get a chance

Oh... I'd really appreciate it if you could move it to a remote branch. Thank you so much your comment!

**Comment by hensmi-amazon** [comment]
Opened https://github.com/aws/amazon-chime-sdk-js/pull/2903 because github doesn't seem to allow me to change the remote branch here.

**Comment by dahae0320** [comment]
Thanks :)

**Pull request closed without merging**
