### PR TITLE
Don't shift existing streams to new transceivers

### PR DESCRIPTION
**Pull request by stopdropandrew**
**Issue #: https://github.com/aws/amazon-chime-sdk-js/issues/831**

**Description of changes:**

Rather than always shifting videos into available transceiver slots, only use previously available slots for *new* videos.

**Testing**

1. Have you successfully run `npm run build:release` locally? *Yes*
2. How did you test these changes? *Added a test for the specific use case*
3. Can these changes be tested using the demo application? *Should be testable via any app. Fixes the issue in our app*
4. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved? *No*
5. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved? *No*

### CODE REVIEW

**Comment by XHatan** [comment]
Hey @alochbau-amzn I think this reverted the fix you made, do you mind taking a look ?

**Comment by alochbau-amzn** [comment]
This is a good change.  It is not reverting my change, but just making sure that the same transceiver is always used for existing remote videos.

**Comment by stopdropandrew** [comment]
I pushed a version that fixes the changelog conflict. What's the timeline on a merge and release?

@alochbau-amzn's commit in 1.19.0 is great, it fixed a high impact but relatively uncommon issue - we we're really excited when we saw that in the changelog, thank you! Unfortunately the issue it introduced, that this pull fixes, is highly occurring but relatively low impact, we can't upgrade our SDK, and it is blocking a new feature in our app, until this is in.

**Comment by alochbau-amzn** [comment]
@stopdropandrew We are doing some maintenance and changes to our CI process and checks.  Once that is done we will re-run the checks and if successful should be able to merge it in.  It would then go out in the subsequent release.

**Comment by alochbau-amzn** [comment]
This has been fixed with a similar change made in https://github.com/aws/amazon-chime-sdk-js/pull/844

**Pull request closed without merging**
