### PR TITLE
Fix #1103: ReceiveAudioInputTask error: undefined is not an object (e…

### LINKED ISSUE #1103: ReceiveAudioInputTask error: undefined is not an object (evaluating 'track.label.indexOf')
**Important:**
INFO-level logs with timestamps.
[AmazonChimeLogs(iOS).txt](https://github.com/aws/amazon-chime-sdk-js/files/6057361/AmazonChimeLogs.iOS.txt)

**Meeting and attendee IDs:**
meeting ID:1b3c7be7-525a-4f3a-b3c6-77ffdd3e7516
attendee ID: 18db81d7-b13a-b410-d332-0a5cda75fdec

**Timeline**
* Just started and joined the meeting.

**Describe the bug**
[Info] 2021-02-28T17:19:31.067Z [INFO] SDK - serial group task AudioVideoStart/1b3c7be7-525a-4f3a-b3c6-77ffdd3e7516/18db81d7-b13a-b410-d332-0a5cda75fdec was canceled due to subtask AudioVideoStart/1b3c7be7-525a-4f3a-b3c6-77ffdd3e7516/18db81d7-b13a-b410-d332-0a5cda75fdec/ReceiveAudioInputTask error: undefined is not an object (evaluating 'track.label.indexOf')

**Screenshots**
No Screenshots.

**Platform**
 - OS: iOS 14.4
 - Browser: ios-webview
 - Browser Version: 605 (605.1.15)
 - Amazon Chime SDK GitHub Commit: [v2.5.0](https://github.com/aws/amazon-chime-sdk-js/releases/tag/v2.5.0)

### PR DESCRIPTION
**Pull request by TheAnkurPanchani**
…valuating 'track.label.indexOf')

**Issue #1103 :**

**Description of changes:** 
Check `track.label` before accessing.

**Testing**

1. Have you successfully run `npm run build:release` locally? **Yes**
2. How did you test these changes? 
3. Can these changes be tested using the demo application? If yes, which demo application can be used to test it? **No**
4. Do you add, modify, or delete public API definitions? If yes, has that been reviewed and approved? **No**
5. Do you change the wire protocol, e.g. the request method? If yes, has that been reviewed and approved? **No**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by XHatan** [comment]
Hey, thanks for the PR. I am wondering how we can trigger this condition ? when will the label of track be undefined ?

**Comment by TheAnkurPanchani** [comment]
@XHatan : You can check issue #1103 for the details. I've raised this PR to fix it.

**Comment by michhyun1** [comment]
@TheAnkurPanchani Thanks for your contribution! I've merged another change that does a bit more than just add a null check. I'll close this PR since it is no longer necessary, but thank you for your efforts to contribute!

**Comment by TheAnkurPanchani** [comment]
@michhyun1 : I don't have much idea about code, so I did that minimal change to make my use case work. I am glad that you are able to find the problem and made generic change based on code context. Happy to help. Happy coding!! 👍

**Pull request closed without merging**
